name: Run Vitest

on:
  workflow_call:
    inputs:
      pre-test:
        type: string

jobs:
  run-vitest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Add Converage Dependencies
        run: pnpm i -D @vitest/coverage-v8@$(cat package.json | jq -r .devDependencies.vitest) $(if [ -f "pnpm-workspace.yaml" ]; then echo "-w"; else echo ; fi)

      - name: Pre Test
        if: inputs.pre-test
        run: ${{ inputs.pre-test }}

      - name: Test
        run: pnpm exec vitest run --coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4
        with:
          files: ./coverage/coverage-final.json

      - name: Uplaod Artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: vitest-coverage-report
          path: coverage
