name: Run Vitest

on:
  workflow_call:
    inputs:
      pre-test:
        type: string

jobs:
  run-vitest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Add Converage Dependencies
        run: pnpm i -D @vitest/coverage-v8@$(cat package.json | jq -r .devDependencies.vitest) $(if [ -f "pnpm-workspace.yaml" ]; then echo "-w"; else echo ; fi)

      - name: Pre Test
        if: inputs.pre-test
        run: ${{ inputs.pre-test }}

      - name: Test
        run: pnpm exec vitest run --coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@015f24e6818733317a2da2edd6290ab26238649a # v5
        with:
          files: ./coverage/coverage-final.json

      - name: Uplaod Artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: vitest-coverage-report
          path: coverage
