name: Run Vitest

on: workflow_call

jobs:
  run-vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Add Converage Dependencies
        run: pnpm i -D @vitest/coverage-v8

      - name: Test
        run: pnpm exec vitest run --coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
        with:
          files: ./coverage/coverage-final.json
