name: Setup Bun

on: workflow_call

jobs:
  setup-bun:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Add Bun to PATH
        run: echo "export PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_ENV
